#! /bin/bash

ROOT_UID=0
DEST_DIR=

# Destination directory
if [ "$UID" -eq "$ROOT_UID" ]; then
  DEST_DIR="/usr/share/themes"
else
  DEST_DIR="$HOME/.themes"
fi

  rm -rf $DEST_DIR/vimix*
  echo -e "\nInstalling vimix..."
# Copying files
  cp -a vimix* $DEST_DIR
  echo -e "\nInstallation complete!"
  notify-send "All done!" "Enjoy vimix!" -i face-smile


